alert("Error! Please enter a valid password");
console.log("Error! Please enter a valid password");
alert("Welcome To Js Land... \nHappy Coading!");
console.log("Welcome To Js Land... \nHappy Coading!");
alert("Welcome To Js Land...");
console.log("Welcome To Js Land...");
alert("Happy Coading!");
console.log("Happy Coading!");
alert("Hello... I can run Js through my web browser's console");
console.log("Hello... I can run Js through my web browser's console");